ibtikar_share_economy_ums_login:
    path:     /login
    defaults: { _controller: IbtikarShareEconomyUMSBundle:User:login }

ibtikar_share_economy_ums_register_customer:
    path:     /register-customer
    defaults: { _controller: IbtikarShareEconomyUMSBundle:User:registerCustomer }
    methods:  POST