ibtikar_share_economy_ums_api_user:
    resource: "@IbtikarShareEconomyUMSBundle/Resources/config/routing/api.yml"
    prefix:   /api

ibtikar_share_economy_ums_login:
    path:     /login
    defaults: { _controller: IbtikarShareEconomyUMSBundle:User:login }

ibtikar_share_economy_ums_logout:
    path:     /logout