ibtikar_share_economy_ums_api_user:
    resource: "@IbtikarShareEconomyUMSBundle/Resources/config/routing/api.yml"
    prefix:   /api

ibtikar_share_economy_ums_user:
    resource: "@IbtikarShareEconomyUMSBundle/Resources/config/routing/user.yml"
    prefix:   /
