ibtikar_share_economy_ums_login:
    path:     /login
    defaults: { _controller: IbtikarShareEconomyUMSBundle:User:login }

ibtikar_share_economy_ums_api_login:
    path:     /api/login
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:login }
    methods:  POST

ibtikar_share_economy_ums_logout:
    path:     /logout

ibtikar_share_economy_ums_register_customer:
    path:     /register-customer
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:registerCustomer }
    methods:  POST
    
ibtikar_share_economy_ums_verify_email:
    path:     /verify-email/{token}
    defaults: { _controller: IbtikarShareEconomyUMSBundle:User:verifyEmail }

ibtikar_share_economy_ums_check_verification_code:
    path:     /check-verification-code
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:checkVerificationCode }
    methods:  GET