services:

    api_operations:
        class: Ibtikar\ShareEconomyUMSBundle\Service\APIOperations
        arguments: [ '@translator', '%locale%' ]

    jwt.authentication_failure_listener:
        class: Ibtikar\ShareEconomyUMSBundle\Listener\AuthenticationFailureListener
        arguments: [ '@translator', '%locale%' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    jwt.authentication_success_listener:
        class: Ibtikar\ShareEconomyUMSBundle\Listener\AuthenticationSuccessListener
        arguments: [ '@api_operations' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    ibtikar.shareeconomy.ums.email_sender:
        class:  Ibtikar\ShareEconomyUMSBundle\Service\EmailSender
        arguments:  ["@doctrine.orm.entity_manager", "@mailer", "@templating", %mailer_user%]