services:
    user_operations:
        class: Ibtikar\ShareEconomyUMSBundle\Service\UserOperations
        arguments: [ '@service_container' ]

    phone_verification_code_business:
        class: Ibtikar\ShareEconomyUMSBundle\Service\PhoneVerificationCodeBusiness
        arguments: [ "%ibtikar_share_economy_ums.verification_code_expiry_minutes%" ]

    jwt.authentication_failure_listener:
        class: Ibtikar\ShareEconomyUMSBundle\Listener\AuthenticationFailureListener
        arguments: [ '@translator', '@user_operations' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    jwt.authentication_success_listener:
        class: '%ibtikar_share_economy_ums.authentication_success_listener_class%'
        arguments: [ '@service_container' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    request.listener.check_api_login:
        class: Ibtikar\ShareEconomyUMSBundle\Listener\CheckAPILogin
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
        arguments: [ '@security.token_storage', '@user_operations' ]

    ibtikar.shareeconomy.ums.email_sender:
        class:  Ibtikar\ShareEconomyUMSBundle\Service\EmailSender
        arguments:  ["@doctrine.orm.entity_manager", "@mailer", "@templating", "%mailer_user%", '@logger']