services:

    request_set_language:
        class: Ibtikar\ShareEconomyUMSBundle\Listener\LanguageChangeListener
        arguments: [ "%accepted_locales%", "%locale%", "@security.token_storage", "@doctrine.orm.entity_manager", "@logger" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: changeRequestLocale, priority: 17 }
            - { name: kernel.event_listener, event: kernel.request, method: changeUserLocale, priority: 7 }

    request_user_update_locale:
        class: Ibtikar\ShareEconomyUMSBundle\Listener\UserLanguageSetListener
        arguments: [ "@session" ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    user_operations:
        class: '%ibtikar_share_economy_ums.user_operations_class%'
        arguments: [ '@service_container' ]

    phone_verification_code_business:
        class: Ibtikar\ShareEconomyUMSBundle\Service\PhoneVerificationCodeBusiness
        arguments: [ "%ibtikar_share_economy_ums.verification_code_expiry_minutes%" ]

    jwt.authentication_failure_listener:
        class: Ibtikar\ShareEconomyUMSBundle\Listener\AuthenticationFailureListener
        arguments: [ '@translator', '@user_operations' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    jwt.authentication_success_listener:
        class: '%ibtikar_share_economy_ums.authentication_success_listener_class%'
        arguments: [ '@service_container' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    request.listener.check_api_login:
        class: Ibtikar\ShareEconomyUMSBundle\Listener\CheckAPILogin
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
        arguments: [ '@security.token_storage', '@user_operations' ]

    ibtikar.shareeconomy.ums.email_sender:
        class:  Ibtikar\ShareEconomyUMSBundle\Service\EmailSender
        arguments:  ["@doctrine.orm.entity_manager", "@mailer", "@templating", "%mailer_user%", '@logger', '@translator']