<?php

namespace Ibtikar\ShareEconomyUMSBundle\Repository;

/**
 * BaseUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Mahmoud Mostafa <mahmoud.mostafa@ibtikar.net.sa>
 */
class BaseUserRepository extends \Doctrine\ORM\EntityRepository
{

}
