<?php

namespace Ibtikar\ShareEconomyUMSBundle\Repository;

/**
 * PhoneVerificationCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @author Karim Shendy <kareem.elshendy@ibtikar.net.sa>
 */
class PhoneVerificationCodeRepository extends \Doctrine\ORM\EntityRepository
{

    public function countTodaysCodes($user)
    {
        $today = new \DateTime();

        return $this->createQueryBuilder('p')
                ->select('count(p.id)')
                ->where('p.user = :user')
                ->andWhere('DATE(p.createdAt) = :today')
                ->setParameters(['user' => $user, 'today' => $today->format('Y-m-d')])
                ->getQuery()
                ->getSingleScalarResult();
    }
}