ibtikar_share_economy_ums_api_user_login:
    path:     /login
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:login }
    methods:  POST

ibtikar_share_economy_ums_api_user_edit_profile_picture:
    path:     /auth/edit-profile-picture
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:editProfilePicture }
    methods:  [POST]

ibtikar_share_economy_ums_api_user_remove_profile_picture:
    path:     /auth/remove-profile-picture
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:removeProfilePicture }
    methods:  [POST]

ibtikar_share_economy_ums_api_user_get_user_info:
    path:     /user-info/{id}
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:getUserInfo }
    methods:  [GET]

ibtikar_share_economy_ums_register_customer:
    path:     /register-customer
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:registerCustomer }
    methods:  POST

ibtikar_share_economy_ums_check_verification_code:
    path:     /check-verification-code/{id}/{code}
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:checkVerificationCode }
    methods:  GET
    requirements:
        id:  \d+
        code:  \d+

ibtikar_share_economy_ums_resend_verification_code:
    path:     /resend-verification-code/{id}
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:resendVerificationCode }
    methods:  GET
    requirements:
        id:  \d+

ibtikar_share_economy_ums_get_verification_remaining_time:
    path:     /verification-remaining-time/{id}
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:getVerificationRemainingTime }
    methods:  GET
    requirements:
        id:  \d+
        
ibtikar_share_economy_ums_get_last_phone_verification_code:
    path:     /get-last-phone-verification-code/{id}
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:getLastPhoneVerificationCode }
    methods:  GET
    requirements:
        id:  \d+

ibtikar_share_economy_ums_update_phone_number:
    path:     /update-phone-number/{id}
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:updatePhoneNumber }
    methods:  POST
    requirements:
        id:  \d+
    
ibtikar_share_economy_ums_update_user_info:
    path:     /auth/update-user-info
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:updateUserInfo }
    methods:  POST

ibtikar_share_economy_ums_is_email_verified:
    path:     /is-email-verified/{id}
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:isEmailVerified }
    methods:  GET
    requirements:
        id:  \d+

ibtikar_share_economy_ums_change_password:
    path:     /auth/change-password
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:changePassword }
    methods:  POST
    
ibtikar_share_economy_ums_send_reset_password_email:
    path:     /send-reset-password-email
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:sendResetPasswordEmail }
    methods:  POST
    
ibtikar_share_economy_ums_resend_verification_email:
    path:     /resend-verification-email
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:resendVerificationEmail }
    methods:  POST
    
ibtikar_share_economy_ums_change_locale:
    path:     /auth/change-locale
    defaults: { _controller: IbtikarShareEconomyUMSBundle:API/User:changeLocale }
    methods:  POST