admin_list:
    path:     /dashboard/admin/list
    defaults: { _controller: IbtikarShareEconomyUMSBundle:Admin:list }

create_admin:
    path:     /dashboard/admin/create
    defaults: { _controller: IbtikarShareEconomyUMSBundle:Admin:create }