ibtikar_share_economy_ums_list_admin_users:
    path:     /dashboard/admin/list
    defaults: { _controller: IbtikarShareEconomyUMSBundle:Admin:list }

delete_user:
    path:     /dashboard/admin/delete/{entityId}
    defaults: { _controller: IbtikarShareEconomyUMSBundle:Admin:delete, entityId:~ }
